#!/usr/bin/python3
##############################################
#
# This is open source software licensed under the Apache License 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
##############################################

from plantgw.plantgw import PlantGateway, SensorConfig
import sys
import signal
import time

def handler(signum, frame):
    res = input("Ctrl-c was pressed. Do you really want to exit? y/n ")
    if res == 'y':
        exit(1)

signal.signal(signal.SIGINT, handler)

def main():
    pg = PlantGateway(config_file_path="/plantgw.yaml")

    def signal_handler(*args):
        print('You pressed Ctrl+C, disconnect mqtt...')
        pg.stop_client()
        sys.exit()

    signal.signal(signal.SIGINT, signal_handler) # Or whatever signal

    pg.subscribe()
    print("subscribe done")
    while True:
        failed_sensors = pg.process_all()
        if len(failed_sensors) > 0:
            print('Could not get data from {}sensor(s): {}.'.format(
                len(failed_sensors),
                SensorConfig.get_name_string(failed_sensors)))
        print("Sleep for {}".format(str(pg.get_frequency())))
        time.sleep(pg.get_frequency())
        

    pg.stop_client()
    # only count the sensors that are NOT fail silent
    num_failed = len([s for s in failed_sensors if not s.fail_silent])
    sys.exit(num_failed)


if __name__ == '__main__':
    main()
